name: update bundle

on:
  workflow_dispatch:
  release:
    types: [created]
jobs:
  run_python_script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
      
    - name: Run Python script
      run: |
        pip install requests
        python build_bundle_url.py
      
    - name: Commit and push changes
      run: |
        git add bundle.json
        git commit -m "update bundle.json [skip ci]"
        git push origin main
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
